package:
  name: pycat
  version: "1.0.0"


source:
  # Assuming the source is from a git repository; replace with your actual source.
  git_url: https://github.com/yourusername/pycat.git
  git_rev: v1.0.0

# replace this with the updated version of the above
source:
  path: ..

  


build:
  noarch: python
  script: python -m pip install .

requirements:
  build:
    - python >=3.9
    - setuptools >=42
    - wheel
  run:
    - python >=3.9
    - aicsimageio
    - aicspylibczi >=3.0.5
    - cellpose
    - matplotlib
    - napari
    - numpy
    - opencv-python-headless
    - pandas
    - pydantic
    - pyqt5
    - torch
    - pywavelets
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - simpleitk

about:
  home: https://github.com/myusername/pycat
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Python Condensate Analysis Toolbox"
  description: "PyCAT is a Python Condensate Analysis Toolbox designed for fluorescence image analysis and bio-image analysis, particularly for biomolecular condensates."
  author: "Christian Neureuter"
  author_email: "christian.neureuter@icloud.com"
  keywords:
    - condensate
    - image analysis
    - fluorescence image analysis
    - napari
    - PyCAT
  classifiers:
    - Programming Language :: Python :: 3
    - License :: OSI Approved :: BSD License
    - Operating System :: OS Independent



  keywords:
    - condensate
    - image analysis
    - fluorescence image analysis
    - napari
    - PyCAT
  author:
    - name: Christian Neureuter
      email: christian.neureuter@icloud.com

extra:
  recipe-maintainers:
    - yourusername