[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "pycat-napari"
version = "1.0.0"
description = "Python Condensate Analysis Toolbox - A napari-based tool for biomolecular condensate analysis"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    {name = "Christian Neureuter", email = "christian.neureuter@icloud.com"}
]

keywords = [
    "condensate",
    "image analysis",
    "fluorescence",
    "microscopy",
    "napari",
    "bio-image",
    "scientific"
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Visualization",
]

dependencies = [
    "aicsimageio",
    "cellpose",
    "matplotlib",
    "napari",
    "numpy>=1.22",
    "opencv-python-headless",
    "pandas",
    "pydantic",
    "pyqt5",
    "torch",
    "pywavelets",
    "scikit-image",
    "scikit-learn",
    "scipy",
    "seaborn",
    "simpleitk",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
    "black",
    "ruff",
    "build",
    "twine",
    "pre-commit",
]

test = [
    "pytest>=7.0",
    "pytest-cov",
    "pytest-qt",
]

docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "myst-parser",
]

arm-mac = [
    "torchvision; platform_system=='Darwin' and platform_machine=='arm64'",
    "torch==2.1.2; platform_system=='Darwin' and platform_machine=='arm64'",
]

devbio = [
    "napari-plugin-engine>=0.1.4",
    "npe2<0.7.0",
    "numpy>=1.21.4",
    "napari-pyclesperanto-assistant",
    "napari-skimage-regionprops",
    "napari-animation",
    "napari-plot-profile",
    "napari-brightness-contrast",
    "napari-plugin-search",
]

[project.urls]
Homepage = "https://github.com/organization/pycat-napari"
Documentation = "https://pycat-napari.readthedocs.io"
Repository = "https://github.com/organization/pycat-napari"
Issues = "https://github.com/organization/pycat-napari/issues"
Changelog = "https://github.com/organization/pycat-napari/blob/main/CHANGELOG.md"

[project.scripts]
run-pycat = "pycat.run_pycat:main"

[tool.hatch.build.targets.wheel]
packages = ["src/pycat"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
addopts = "-v --cov=pycat --cov-report=term-missing"
testpaths = ["tests"]
qt_api = "pyqt5"

[tool.black]
line-length = 88
target-version = ["py39"]
include = '\.pyi?$'

[tool.ruff]
select = ["E", "F", "B", "I"]
ignore = ["E501"]
line-length = 88
target-version = "py39"