#!/usr/bin/env python3
"""Build the QC exemplar gallery as documentation: PNGs plus a markdown page.

    python tools/build_qc_gallery.py [output_dir]

Writes ``docs/qc_gallery/`` by default: one side-by-side PNG per defect, and an
``index.md`` with the *Image → Assessment → Interpretation → Recommendation* text for each.

The verdicts are **computed by calling the real QC metrics** on the real images — not written
down. If a metric stops firing on its own exemplar, this script says so and exits non-zero. **A
teaching example that no longer matches the software is worse than none.**
"""

import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src'))


def _panel(ax, img, title, verdict, is_stack):
    """One image with its QC verdict burned into the caption."""
    frame = np.asarray(img)
    if is_stack:
        frame = frame[-1]                       # the LAST frame: bleaching and drift show there

    ax.imshow(frame, cmap='gray')
    ax.set_xticks([])
    ax.set_yticks([])

    status = verdict.get('status', '?')
    colour = {'good': '#2e7d32', 'warn': '#ef6c00',
              'bad': '#c62828'}.get(status, '#555555')

    import textwrap
    ax.set_title("\n".join(textwrap.wrap(title, 42)), fontsize=9, pad=6)
    ax.set_xlabel("\n".join(textwrap.wrap(
        f"{status.upper()} — {verdict.get('headline', '')}", 46)),
        fontsize=8, color=colour)

    for spine in ax.spines.values():
        spine.set_edgecolor(colour)
        spine.set_linewidth(2.0)


def main(out_dir):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    from pycat.toolbox.qc_gallery import build_gallery

    os.makedirs(out_dir, exist_ok=True)
    gallery = build_gallery()

    failures = []
    lines = [
        "# What a quality problem looks like",
        "",
        "Each panel below shows a **clean** acquisition beside one carrying a single, known "
        "defect — and what PyCAT's QC says about each.",
        "",
        "> **These images are SIMULATED.** They are reference exemplars, generated with a "
        "known physical corruption, so that a scientist can see what a defect looks like and "
        "how their own data compares. **They are not an acquisition standard** — a real image "
        "is not expected to look like a synthetic one. Each caption gives the exact parameter "
        "that produced the defect.",
        "",
        "The verdicts are **computed** — this page is generated by calling the real QC metrics "
        "on the real images. If a metric stopped detecting its own defect, the build would fail.",
        "",
        "---",
        "",
    ]

    for entry in gallery:
        clean_status = entry['clean_verdict']['status']
        bad_status = entry['degraded_verdict']['status']

        if clean_status not in ('good', 'info', 'na') or bad_status not in ('warn', 'bad'):
            failures.append(
                f"{entry['key']}: clean={clean_status}, degraded={bad_status} — the exemplar "
                f"does not demonstrate the defect it claims to")

        fig, axes = plt.subplots(1, 2, figsize=(9.5, 5.6))
        _panel(axes[0], entry['clean'], 'Clean', entry['clean_verdict'], entry['is_stack'])
        _panel(axes[1], entry['degraded'], f"Degraded — {entry['params']}",
               entry['degraded_verdict'], entry['is_stack'])
        fig.suptitle(entry['title'], fontsize=12, fontweight='bold')
        fig.tight_layout(rect=(0, 0.02, 1, 0.94))

        png = f"{entry['key']}.png"
        fig.savefig(os.path.join(out_dir, png), dpi=110)
        plt.close(fig)

        lines += [
            f"## {entry['title']}",
            "",
            f"![{entry['title']}]({png})",
            "",
            f"*Simulated: {entry['params']}. Detected by `{entry['metric']}`.*",
            "",
            "**What it looks like.**  " + entry['looks_like'],
            "",
            "**What it costs you.**  " + entry['costs'],
            "",
            "**How to fix it.**  " + entry['fix'],
            "",
            f"**Read more.**  [{entry['wiki'][0]}]({entry['wiki'][1]}) · "
            f"{entry['cite'][0]} [doi]({entry['cite'][1]})",
            "",
        ]
        if entry.get('cite_quote'):
            lines += [f"> {entry['cite_quote']}", ""]
        lines += ["---", ""]

    lines += [
        "## A caveat the gallery itself taught us",
        "",
        "The vignetting exemplar uses a **flat background**, not the four-cell reference scene — "
        "because four cells arranged in a ring **genuinely are a radial intensity pattern**, and "
        "`qc_vignetting` reads that clean scene as *bad*.",
        "",
        "**The metric is not wrong. The scene is.** This is a real caveat for a sparse field: if "
        "your cells happen to sit toward the centre, a vignetting score will say so, and it is "
        "reporting where your cells are rather than how your lamp is behaving. Acquire a "
        "flat-field reference if the answer matters.",
        "",
    ]

    with open(os.path.join(out_dir, 'index.md'), 'w', encoding='utf-8') as fh:
        fh.write("\n".join(lines))

    print(f"  wrote {len(gallery)} exemplars to {out_dir}")

    if failures:
        print("\n  EXEMPLARS THAT DO NOT TEACH:")
        for f in failures:
            print(f"    {f}")
        return 1

    print("  every exemplar trips its own metric")
    return 0


if __name__ == '__main__':
    target = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), '..', 'docs', 'qc_gallery')
    sys.exit(main(target))
